### ISSUE TITLE
Compilation Error

### ISSUE THREAD

**Issue by zainmehdi** [jakobwilm/ThetaHDR#1]
error: ‘USB_CLASS_PTP’ was not declared in this scope
         USB_CLASS_PTP)||force)
   Hi I am getting this error while compiling. Can you please let me know if some file is missing ?

**Comment by jakobwilm** [comment]
Sorry, I cannot say.

**Comment by zainmehdi** [comment]
For anyone having the same issue its because of libusb version. Make sure you are using the latest version and this error wont appear.
